# Copyright 2026 Phillip Cloud
# Licensed under the Apache License, Version 2.0

baseURL = "/docs/"
title = "micasa docs"
languageCode = "en-us"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "manni"
noClasses = false

[params]
description = "Documentation for micasa, a terminal UI for tracking everything about your home."
